# Generated by Codex on 2026-02-17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_add_auction_mechanics"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="wage_offer_weekly",
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="bid",
            name="reserved_transfer_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="bid",
            name="reserved_wage_weekly",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
