# Generated by Django 5.2.11 on 2026-02-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_bid_finance_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("BID_PLACED", "Bid placed"),
                    ("BID_REPLACED", "Bid replaced"),
                    ("BID_ACCEPTED", "Bid accepted"),
                    ("AUCTION_CLOSED", "Auction closed"),
                    ("AUCTION_EXTENDED", "Auction extended"),
                ],
                max_length=30,
            ),
        ),
    ]
