# Generated by Django 6.0.2 on 2026-02-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_alter_auctionevent_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="deadline",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="auction",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("ACCEPTED", "Accepted"),
                    ("CLOSED", "Closed"),
                ],
                db_index=True,
                default="OPEN",
                max_length=20,
            ),
        ),
    ]
