# Generated by Django 6.0.2 on 2026-02-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("OUTBID", "Outbid"),
                    ("OFFER_RECEIVED", "Offer received"),
                    ("OFFER_ACCEPTED", "Offer accepted"),
                    ("OFFER_REJECTED", "Offer rejected"),
                    ("OFFER_COUNTERED", "Offer countered"),
                    ("OFFER_EXPIRING", "Offer expiring"),
                    ("LISTING_NEW_OFFER", "Listing new offer"),
                    ("AUCTION_ENDING", "Auction ending"),
                    ("AUCTION_BID_ACCEPTED", "Auction bid accepted"),
                    ("DEAL_COMPLETED", "Deal completed"),
                    ("DEAL_COLLAPSED", "Deal collapsed"),
                    ("PLAYER_AVAILABLE", "Player available"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
