# Generated by Django 5.2.11 on 2026-02-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_player_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='vendor_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
