# Generated by Django 5.2.11 on 2026-02-21 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_club_squad_target"),
        ("players", "0005_player_vendor_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts",
                to="accounts.club",
            ),
        ),
    ]
