[build]
builder = "DOCKERFILE"
dockerfilePath = "docker/web/Dockerfile"

[deploy]
healthcheckPath = "/accounts/login/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
