# Generated by Django 6.0.2 on 2026-02-22 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_auction_index_status_deadline"),
        ("deals", "0001_initial"),
        (
            "marketplace",
            "0004_rename_marketplace_offer_status_to_club_idx_marketplace_status_0c934a_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="auction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deal",
                to="auctions.auction",
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="offer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deal",
                to="marketplace.offer",
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_PROGRESS", "In progress"),
                    ("PENDING_COMPLETION", "Pending completion"),
                    ("COMPLETED", "Completed"),
                    ("COLLAPSED", "Collapsed"),
                ],
                db_index=True,
                default="IN_PROGRESS",
                max_length=20,
            ),
        ),
    ]
