# Generated by Django 6.0.2 on 2026-02-20 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("world", "0002_profiles"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="worldclub",
            name="uq_worldclub_vendor_team_league_season",
        ),
        migrations.RemoveConstraint(
            model_name="worldclubprofile",
            name="uq_worldclubprofile_vendor_club_league_season",
        ),
        migrations.RemoveConstraint(
            model_name="worldplayer",
            name="uq_worldplayer_vendor_player",
        ),
        migrations.RemoveConstraint(
            model_name="worldplayerprofile",
            name="uq_worldplayerprofile_vendor_player_league_season",
        ),
        migrations.RemoveConstraint(
            model_name="worldsquadmembership",
            name="uq_worldmembership_vendor_club_player_league_season",
        ),
        migrations.RemoveField(
            model_name="worldplayerprofile",
            name="current_club",
        ),
        migrations.RemoveField(
            model_name="worldplayerprofile",
            name="player",
        ),
        migrations.RemoveField(
            model_name="worldsquadmembership",
            name="club",
        ),
        migrations.RemoveField(
            model_name="worldsquadmembership",
            name="player",
        ),
        migrations.DeleteModel(
            name="WorldClubProfile",
        ),
        migrations.DeleteModel(
            name="WorldPlayerProfile",
        ),
        migrations.DeleteModel(
            name="WorldClub",
        ),
        migrations.DeleteModel(
            name="WorldPlayer",
        ),
        migrations.DeleteModel(
            name="WorldSquadMembership",
        ),
    ]
