# Generated by Codex on 2026-02-17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorSyncState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("vendor", models.CharField(db_index=True, default="api_football", max_length=100)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("error_count", models.IntegerField(default=0)),
                ("last_error", models.TextField(blank=True, default="")),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("vendor",), name="unique_vendor_sync_state")
                ]
            },
        ),
        migrations.CreateModel(
            name="PlayerVendorMap",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("vendor", models.CharField(db_index=True, default="api_football", max_length=100)),
                ("vendor_player_id", models.BigIntegerField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_map",
                        to="players.player",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("vendor", "vendor_player_id"), name="unique_vendor_player_id"
                    ),
                    models.UniqueConstraint(fields=("vendor", "player"), name="unique_vendor_player"),
                ]
            },
        ),
        migrations.CreateModel(
            name="PlayerStatsSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("vendor", models.CharField(db_index=True, default="api_football", max_length=100)),
                ("as_of", models.DateTimeField(db_index=True)),
                ("season", models.IntegerField(blank=True, db_index=True, null=True)),
                ("league_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("payload", models.JSONField(default=dict)),
                ("minutes", models.IntegerField(blank=True, null=True)),
                ("goals", models.IntegerField(blank=True, null=True)),
                ("assists", models.IntegerField(blank=True, null=True)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats_snapshots",
                        to="players.player",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("player", "vendor", "season", "league_id", "as_of"),
                        name="unique_stats_snapshot",
                    )
                ]
            },
        ),
    ]
