# Generated by Codex on 2026-02-17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendorsyncstate",
            name="vendor",
            field=models.CharField(db_index=True, default="api_sports_v3", max_length=100),
        ),
        migrations.AlterField(
            model_name="playervendormap",
            name="vendor",
            field=models.CharField(db_index=True, default="api_sports_v3", max_length=100),
        ),
        migrations.AlterField(
            model_name="playerstatssnapshot",
            name="vendor",
            field=models.CharField(db_index=True, default="api_sports_v3", max_length=100),
        ),
    ]
