# Generated by Codex on 2026-02-17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0001_initial"),
        ("stats", "0002_update_vendor_defaults"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerForm",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("vendor", models.CharField(db_index=True, default="api_sports_v3", max_length=100)),
                ("as_of", models.DateTimeField(db_index=True)),
                ("season", models.IntegerField(blank=True, db_index=True, null=True)),
                ("league_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("window_games", models.IntegerField(default=5)),
                ("form_score", models.FloatField(db_index=True, default=0.0)),
                ("trend", models.FloatField(blank=True, null=True)),
                ("avg_rating", models.FloatField(blank=True, null=True)),
                ("minutes", models.IntegerField(blank=True, null=True)),
                ("goals", models.IntegerField(blank=True, null=True)),
                ("assists", models.IntegerField(blank=True, null=True)),
                ("key_metrics", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form",
                        to="players.player",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("player", "vendor", "season", "league_id", "window_games"),
                        name="unique_player_form_window",
                    )
                ]
            },
        ),
    ]
