# Generated by Django 5.2.11 on 2026-02-20 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_clubprofile_vendor_id'),
        ('players', '0005_player_vendor_id'),
        ('stats', '0004_player_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(blank=True, default='', max_length=50)),
                ('league_id', models.IntegerField(db_index=True)),
                ('season', models.IntegerField(db_index=True)),
                ('position', models.CharField(blank=True, default='', max_length=50)),
                ('minutes', models.IntegerField(blank=True, null=True)),
                ('goals', models.IntegerField(blank=True, null=True)),
                ('assists', models.IntegerField(blank=True, null=True)),
                ('avg_rating', models.FloatField(blank=True, null=True)),
                ('form_score', models.FloatField(blank=True, null=True)),
                ('trend', models.FloatField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.clubprofile')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_stats', to='players.player')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('player', 'vendor', 'league_id', 'season'), name='uq_playerstats_player_vendor_league_season')],
            },
        ),
    ]
