# Generated by Django 6.0.2 on 2026-02-20 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0006_populate_vendor_ids"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="playervendormap",
            name="unique_vendor_player_id",
        ),
        migrations.RemoveConstraint(
            model_name="playervendormap",
            name="unique_vendor_player",
        ),
        migrations.DeleteModel(
            name="PlayerVendorMap",
        ),
    ]
