# Generated by Codex on 2026-02-17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClubFinance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("transfer_budget_total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("wage_budget_total_weekly", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("transfer_reserved", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("wage_reserved_weekly", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("transfer_committed", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("wage_committed_weekly", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finance",
                        to="accounts.clubprofile",
                    ),
                ),
            ],
        ),
    ]
