# Generated by Django 5.2.11 on 2026-02-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_clubprofile_marketplace_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubprofile',
            name='vendor_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
