# Generated by Django 6.0.2 on 2026-02-20 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0003_listing_status_visibility_index"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="offer",
            new_name="marketplace_status_0c934a_idx",
            old_name="marketplace_offer_status_to_club_idx",
        ),
        migrations.RenameIndex(
            model_name="offer",
            new_name="marketplace_status_f6e743_idx",
            old_name="marketplace_offer_status_from_club_idx",
        ),
        migrations.RenameIndex(
            model_name="offer",
            new_name="marketplace_player__07ee98_idx",
            old_name="marketplace_offer_player_status_idx",
        ),
    ]
